version: "2"
services:

  fpm:
    image: php:7.1.1-fpm-alpine
    container_name: y2bsearch_fpm
    links:
      - mysql
    volumes:
      - ../y2bsearch:/y2bsearch/

  nginx:
    image: nginx:alpine
    container_name: y2bsearch_nginx
    ports:
      - "80:80"
    links:
      - fpm
    volumes_from:
      - fpm
    volumes:
      - ./nginx/config/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    build: mysql
    container_name: y2bsearch_mysql
    ports:
      - "3306:3306"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    container_name: y2bsearch_elasticsearch
    environment:
      - ELASTIC_VER="5.1.1"
    volumes:
      - ./elasticsearch/data:/usr/share/java/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

#  builder:
#    build: builder
#    container_name: y2bsearch_builder
#    volumes_from:
#      - fpm
#    command: "composer install -d /y2bsearch"
